bonitoo-io/selenium-accept-infl2

etc/test-data/alpha_dashboard.json, etc/test-data/tau_ceti_dashboard.json, features/dashboards/dashboards.feature, src/pages/dashboards/dashboardsPage.js, src/pages/dataExplorer/dataExplorerPage.js, src/pages/home/homePage.js, src/pages/loadData/bucketsTab.js, src/pages/settings/membersTab.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/step_definitions/home/homeStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/dashboardsSteps.js, src/steps/dataExplorer/dataExplorerSteps.js, src/steps/home/homeSteps.js, src/steps/settings/labelsSteps.js, src/steps/settings/variablesSteps.js, src/utils/influxUtils.js
Merge additional dashboard tests
=> Additional dashboard tests

cucumber.js, features/dashboards/dashboard.feature, features/settings/templates.feature, package.json, src/pages/basePage.js, src/pages/dashboards/cellEditOverlay.js, src/pages/dashboards/dashboardPage.js, src/pages/dashboards/dashboardsPage.js, src/pages/dataExplorer/dataExplorerPage.js, src/pages/home/homePage.js, src/pages/loadData/tokensTab.js, src/pages/settings/orgProfileTab.js, src/pages/settings/templatesTab.js, src/pages/settings/variablesTab.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js
More Dashboard Tests and selector sync update
=> Dashboard Tests - and selector sync update

features/dashboards/dashboard.feature, features/loadData/telegrafs.feature, src/pages/basePage.js, src/pages/dashboards/cellEditOverlay.js, src/pages/dashboards/dashboardPage.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js, src/steps/dashboards/dashboardsSteps.js, src/steps/settings/templatesSteps.js, src/utils/influxUtils.js
Sync with recent changes in Telegrafs and add more dashboards tests
=> Telegraf fixes and Dashboard update

features/loadData/buckets.feature, src/pages/basePage.js, src/pages/dashboards/dashboardsPage.js, src/pages/loadData/bucketsTab.js, src/pages/settings/templatesTab.js, src/pages/settings/variablesTab.js, src/step_definitions/loadData/bucketsStepDefs.js, src/steps/dashboards/dashboardSteps.js, src/steps/loadData/bucketsSteps.js
Move latest sync changes to circle-ci branch
=> Latest sync to circle-ci branch

features/dashboards/cellEdit.feature, features/dashboards/dashboard.feature, features/settings/variables.feature, features/signin/signin.feature, src/pages/dashboards/cellEditOverlay.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js, src/steps/settings/templatesSteps.js, src/utils/influxUtils.js
Fix name dashboard issue and add cell edit tests
=> First Cell Edit Tests and Name dashboard fix

features/dashboards/cellEdit.feature, features/dashboards/dashboard.feature, features/settings/variables.feature, src/pages/dashboards/cellEditOverlay.js, src/pages/settings/variablesTab.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardStepDefs.js, src/step_definitions/settings/variablesStepDefs.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/loadData/telegrafsSteps.js, src/steps/loadData/tokensSteps.js, src/steps/settings/variablesSteps.js
All tests green in jenkins test stage
=> Jenkins stable check point

features/dashboards/cellEdit.feature, features/dashboards/dashboard.feature, src/pages/dashboards/cellEditOverlay.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js
Synching latest tests with Circle CI nightly
=> synch latest tests

features/dashboards/cellEdit.feature, src/pages/dashboards/cellEditOverlay.js, src/pages/dashboards/dashboardPage.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js
Merge latest cellEdit tests to CircleCi branch
=> Merge latest cellEdit tests

features/dashboards/cellEdit.feature, features/dashboards/dashboards.feature, features/loadData/telegrafs.feature, features/settings/variables.feature, src/pages/basePage.js, src/pages/dashboards/cellEditOverlay.js, src/pages/dashboards/dashboardPage.js, src/pages/dashboards/dashboardsPage.js, src/pages/loadData/bucketsTab.js, src/pages/loadData/telegrafsTab.js, src/pages/settings/membersTab.js, src/pages/settings/variablesTab.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/dashboards/dashboardStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/step_definitions/home/homeStepDefs.js, src/step_definitions/loadData/bucketsStepDefs.js, src/step_definitions/loadData/clientLibStepDefs.js, src/step_definitions/loadData/telegrafStepDefs.js, src/step_definitions/settings/variablesStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/dashboards/dashboardSteps.js, src/steps/dashboards/dashboardsSteps.js, src/steps/loadData/bucketsSteps.js, src/steps/loadData/clientLibsSteps.js, src/steps/loadData/telegrafsSteps.js, src/steps/settings/variablesSteps.js, src/utils/influxUtils.js
Adding new Cell Edit Tests 
Fixes data-testids
=> New Cell Edit tests and fix buckets data-testids

features/dashboards/cellEdit.feature, src/pages/dashboards/cellEditOverlay.js, src/pages/loadData/telegrafsTab.js, src/pages/settings/orgProfileTab.js, src/pages/settings/templatesTab.js, src/steps/baseSteps.js
Some fixes for recent test failures
=> Some fixes for recent failures

features/dashboards/cellEdit.feature, src/step_definitions/settings/variablesStepDefs.js
Small change to get around issue in circleCI
=> check cellEdit issue on CircleCi

features/dashboards/cellEdit.feature, features/dashboards/dashboards.feature, src/pages/dashboards/cellEditOverlay.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/steps/dashboards/cellOverlaySteps.js, src/utils/influxUtils.js
sync with dashboard issue fixes
=> sync with dashboard issue fixes

features/dashboards/cellEdit.feature, src/pages/dashboards/cellEditOverlay.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/steps/dashboards/cellOverlaySteps.js
add 1 test and sync with UI changes
=> tests: refresh rate test and fix change to add function

features/loadData/buckets.feature, src/pages/dashboards/cellEditOverlay.js, src/pages/loadData/bucketsTab.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/loadData/bucketsStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/loadData/bucketsSteps.js
sync with changes to  buckets. 
start variables tests.
=> tests: sync buckets tests and start variables

features/dashboards/variables.feature
=> test: adding variables tests

src/steps/influx/influxSteps.js
Troubleshoot timing issue in CircleCI tests
=> troubleshoot: timing issue in menus

src/steps/influx/influxSteps.js
Why is circleci failing now at this point.
=> troubleshoot:  check timing of menu clicks

cucumber.js, hooks.js, src/step_definitions/common/commonStepDefs.js, src/steps/baseSteps.js
Writes messages in console to err log on failure.
=> chore: add hook for writing console messages to error log

.circleci/config.yml, features/signin/signin.feature, src/pages/dashboards/dashboardPage.js, src/pages/signin/signinPage.js, src/step_definitions/signin/signinStepDefs.js, src/steps/signin/signinSteps.js
=> check: code change and build issues

features/dashboards/cellEdit.feature, features/dashboards/dashboard.feature, features/dashboards/dashboards.feature, features/dashboards/noteCell.feature, features/dashboards/variables.feature, features/influx/influx.feature, features/loadData/buckets.feature, features/loadData/clientlib.feature, features/loadData/scrapers.feature, features/loadData/telegrafs.feature, features/loadData/tokens.feature, features/monitoring/alerts.feature, features/settings/labels.feature, features/settings/settings.feature, features/settings/templates.feature, features/settings/variables.feature, src/pages/dashboards/dashboardsPage.js, src/pages/influxPage.js, src/pages/loadData/loadDataPage.js, src/steps/dashboards/dashboardSteps.js, src/steps/dashboards/dashboardsSteps.js, src/steps/influx/influxSteps.js, src/steps/loadData/telegrafsSteps.js, src/steps/monitoring/monitoringSteps.js, src/steps/settings/settingsSteps.js, src/utils/influxUtils.js
Synchronizing tests with new nav menu changes.  
1. Issue outstanding. 
https://github.com/influxdata/influxdb/issues/17642
=> Update: Sync tests with new nav menu changes

features/dashboards/cellEdit.feature, features/dashboards/dashboard.feature, features/dashboards/dashboards.feature, features/dashboards/noteCell.feature, features/dashboards/variables.feature, features/homePage/homePage.feature, features/influx/influx.feature, features/loadData/buckets.feature, features/loadData/clientlib.feature, features/loadData/loadData.feature, features/loadData/scrapers.feature, features/loadData/telegrafs.feature, features/loadData/tokens.feature, features/monitoring/alerts.feature, features/onboarding/onboarding.feature, features/settings/labels.feature, features/settings/settings.feature, features/settings/templates.feature, features/settings/variables.feature, features/signin/signin.feature, scripts/Dockerfile.bonitoo
Tagging allows us to run or skip specific tests (or sets of them eventually, possibly even in parallel :crossed_fingers:)
=> Add tags to tests

features/monitoring/alerts.feature, features/onboarding/onboarding.feature, src/pages/basePage.js, src/pages/monitoring/alertsPage.js, src/pages/monitoring/checkEditPage.js, src/step_definitions/monitoring/checkEditStepDefs.js, src/step_definitions/monitoring/monitoringStepDefs.js, src/steps/baseSteps.js, src/steps/monitoring/checkEditSteps.js, src/steps/monitoring/monitoringSteps.js
Comment out failing password test and new alert tests
=> update: comment password check and new alert tests

features/dashboards/dashboard.feature, features/dashboards/dashboards.feature, features/homePage/homePage.feature, features/loadData/buckets.feature, features/loadData/scrapers.feature, features/loadData/telegrafs.feature, features/onboarding/onboarding.feature, scripts/Dockerfile.bonitoo
This tags tests currently failing due to changes in influxdb
Tested against https://github.com/influxdata/influxdb/commit/29918a45df27b65d0e1ccd63f5eb88ec24509227
=> Tag failing tests

features/dashboards/dashboards.feature, features/monitoring/alerts.feature, hooks.js, src/pages/basePage.js, src/pages/loadData/bucketsTab.js, src/pages/monitoring/alertsPage.js, src/pages/monitoring/checkEditPage.js, src/step_definitions/common/commonStepDefs.js, src/step_definitions/dashboards/dashboardsStepDefs.js, src/step_definitions/monitoring/checkEditStepDefs.js, src/step_definitions/monitoring/monitoringStepDefs.js, src/steps/baseSteps.js, src/steps/dashboards/dashboardsSteps.js, src/steps/monitoring/checkEditSteps.js, src/steps/monitoring/monitoringSteps.js, src/utils/influxUtils.js
Use new bucket selectors 
Fix live data gen not switching off
=> update: better bucket selectors and fix live data gen 

features/influx/influx.feature, src/pages/influxPage.js, src/pages/organization/organizationPage.js, src/step_definitions/influx/influxStepDefs.js, src/step_definitions/organization/organizationStepDefs.js, src/steps/influx/influxSteps.js, src/steps/organization/organizationSteps.js
Completed a basic navigation menu coverage in the influx.feature test. Added a click check for menu items User and Org.
=> Issue #30 - Complete basic navigation menu coverage

features/influx/influx.feature, features/monitoring/alerts.feature, src/pages/influxPage.js, src/pages/loadData/bucketsTab.js, src/pages/monitoring/alertsPage.js, src/pages/monitoring/checkEditPage.js, src/pages/organization/organizationPage.js, src/step_definitions/dashboards/cellOverlayStepDefs.js, src/step_definitions/influx/influxStepDefs.js, src/step_definitions/monitoring/checkEditStepDefs.js, src/step_definitions/monitoring/monitoringStepDefs.js, src/step_definitions/organization/organizationStepDefs.js, src/steps/dashboards/cellOverlaySteps.js, src/steps/influx/influxSteps.js, src/steps/monitoring/checkEditSteps.js, src/steps/monitoring/monitoringSteps.js, src/steps/organization/organizationSteps.js
Add scenarios for left nav enu orgs and users
=> tests: scenarios for menu orgs and users

features/monitoring/alerts.feature, src/pages/basePage.js, src/pages/monitoring/alertsPage.js, src/step_definitions/loadData/scrapersStepDefs.js, src/step_definitions/monitoring/monitoringStepDefs.js, src/steps/baseSteps.js, src/steps/monitoring/monitoringSteps.js
Sync with new notifications selectors
=> update: sync with new notifications selectors

features/monitoring/alerts.feature, src/pages/monitoring/alertsPage.js, src/pages/monitoring/checkStatusHistoryPage.js, src/step_definitions/monitoring/checkStatusHistoryStepDefs.js, src/step_definitions/monitoring/monitoringStepDefs.js, src/steps/monitoring/checkStatusHistorySteps.js, src/steps/monitoring/monitoringSteps.js, src/utils/influxUtils.js
sync new alerts tests to master
=> tests: sync new alerts tests 

features/dashboards/dashboards.feature, src/pages/influxPage.js, src/step_definitions/onboarding/onboardStepDefs.js, src/steps/influx/influxSteps.js
synch selectors with new nav changes
=> update: synch with nav changes 

etc/test-data/test_deadman_crit_check.json, etc/test-data/test_threshold_check.json, features/influx/influx.feature, features/monitoring/history.feature, src/step_definitions/common/commonStepDefs.js, src/utils/influxUtils.js
Commented out test for menu orgs which is no loner needed
=> update: comment out test for menu orgs

features/onboarding/onboarding.feature, src/steps/onboarding/onboardingSteps.js
sync recent onboarding test with recent changes
=> update: sync onboarding test with recent changes

features/monitoring/history.feature, src/pages/monitoring/checkStatusHistoryPage.js, src/step_definitions/monitoring/checkStatusHistoryStepDefs.js, src/steps/monitoring/checkStatusHistorySteps.js
add click through test for history
=> tests: add click through test for history

etc/influxdb-e2e/sync-from-influx.sh, etc/influxdb-e2e/sync.last, scripts/Dockerfile, src/pages/loadData/telegrafsTab.js, src/pages/monitoring/checkEditPage.js, src/pages/settings/variablesTab.js
Update selectors for some popus
=> update: selectors for some popups

.circleci/config.yml, package.json, src/pages/monitoring/checkStatusHistoryPage.js, src/steps/monitoring/checkStatusHistorySteps.js
=> update: chromedriver update

.circleci/config.yml, features/dataExplorer/dataExplorer.feature, package.json, src/pages/dataExplorer/dataExplorerPage.js, src/step_definitions/dataExplorer/dataExplorerStepDefs.js, src/steps/dataExplorer/dataExplorerSteps.js
adding new data-explorer tests
=> update: add new data-explorer tests
